services:
  - type: web
    name: chatapp-backend
    rootDir: backend
    env: node
    buildCommand: npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
